# -*- coding: utf-8 -*-
"""Matplotlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-xw8obDcWYbRKkZ8PjkbXxu_tN6duMzD
"""

!pip install matplotlib

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

x = np.array([1, 2, 3, 4, 5, 6, 7])

plt.hist(x, bins=13) # bins=No of bars you want to show

x = np.array([1, 2, 3, 4, 5, 6, 7])
plt.hist(x, bins=13) # bins=No of bars you want to show
plt.show()

x = np.array([1, 2, 3, 4, 5, 6, 7])
y = np.array([0.1, 0.2, 0.25, 0.4, 0.5, 0.75, 1])
plt.bar(x, y)
plt.show()

x = np.array([1, 2, 3, 4, 5, 6, 7])
y = np.array([10, 2, 5, 8, 15, 20, 9])
plt.scatter(x, y)
plt.show()

x = np.array([1, 2, 3, 4, 5, 6, 7])
y = np.array([10, 2, 5, 8, 15, 20, 9])
plt.scatter(x, y)
plt.vlines(x, 0, y, linestyle="dotted") # x, ymin, ymax 
plt.hlines(y, 0, x, linestyle="dotted") # y, xmin, xmax
plt.show()

x = np.array([1, 2, 3, 4, 5, 6,7])
plt.plot(x)
plt.show()

x = np.array([1, 2, 3, 4, 5, 6,7])
y = x ** 2
plt.plot(x, y)
plt.show()

x = np.array([1, 2, 3, 4, 5, 6,7])
y = x ** 2
plt.plot(x, y)
plt.xlabel("X values")
# plt...("Y Values")
plt.show()

x = np.array([1, 2, 3, 4, 5, 6,7])
y = x ** 2
plt.plot(x, y, c="r")
plt.show()

x = np.array([1, 2, 3, 4, 5, 6,7])
y = x ** 2
plt.plot(x, y, "r")
plt.show()

x = np.array([1, 2, 3, 4, 5, 6,7])
y = x ** 2
plt.plot(x, y, "ro")
plt.show()

# https://matplotlib.org/stable/api/markers_api.html
x = np.array([1, 2, 3, 4, 5, 6,7])
y = x ** 2
plt.plot(x, y, "r^")
plt.plot(x, x, "b|")
plt.plot(x, x**3, "g<")
plt.show()

x = np.array([1, 2, 3, 4, 5, 6,7])
y = x ** 2
plt.plot(x, y)
plt.plot(x, y+10, linewidth=4)
plt.plot(x, y+20, linewidth=7)
plt.show()

x = np.array([10, 30, 40, 20])
y = np.array(["R", "Julia", "Python", "Java"])
colors = ["blue", "orange", "red", "grey"]
plt.pie(x, labels=y, colors=colors)
plt.show()

plt.pie(x, labels=y, colors=colors, radius=1.5)
plt.show()

plt.pie(x, labels=y, 
        colors=colors,
        radius=1.5,
        explode=(0, 0, 0.2, 0)
        )
plt.show()

plt.pie(x, labels=y, 
        colors=colors,
        radius=1.5,
        explode=(0, 0, 0.2, 0),
        shadow=True
        )
plt.show()

plt.pie(x, labels=y, 
        colors=colors,
        radius=1.5,
        explode=(0, 0, 0.2, 0),
        shadow=True,
        autopct="%1.2f%%"
        )
plt.show()

plt.pie(x, labels=y, 
        colors=colors,
        radius=1.5,
        explode=(0, 0, 0.2, 0),
        shadow=True,
        autopct="%1.2f%%",
        startangle=-30
        )
plt.show()

x1 = np.arange(0, 20, 0.1)
x2 = np.arange(0, 20, 0.2)

plt.figure()

plt.subplot(211)
plt.plot(x1, np.cos(x1))

plt.subplot(212)
plt.plot(x2, np.sin(x2), 'r-.')
plt.grid()
plt.show()

x1 = np.arange(0, 20, 0.1)
x2 = np.arange(0, 20, 0.2)

plt.figure(figsize=(10, 5), dpi=300)

# plt.subplot(nrows, ncols, index)
plt.subplot(221)
plt.plot(x1, np.cos(x1))

plt.subplot(222)
plt.plot(x2, np.sin(x2), 'r-.')
plt.grid()
plt.show()

# https://moonbooks.org/Articles/How-to-plot-a-normal-distribution-with-matplotlib-in-python-/
import scipy.stats

x_min = 0.0
x_max = 16.0

mean = 8.0 
std = 2.0

x = np.linspace(x_min, x_max, 100)

# probability density function (PDF)
y = scipy.stats.norm.pdf(x, mean, std)

plt.plot(x, y, color='coral')

plt.grid()

plt.xlim(x_min, x_max)
plt.ylim(0, 0.25)

plt.title('How to plot a normal distribution in python with matplotlib',fontsize=10)

plt.xlabel('x')
plt.ylabel('Normal Distribution')

plt.savefig("normal_distribution.png")
plt.show()

x = np.array([1, 2, 3, 4, 5, 6, 7])
y = x ** 2

plt.figure(figsize=(10, 5), dpi=300)

plt.subplot(311)
plt.scatter(x, y)
plt.title("Scatter plot")

plt.subplot(312)
plt.plot(x, y, 'r--', linewidth=5)
plt.grid()
plt.title("Line plot")

plt.subplot(313)
plt.bar(x, y)
plt.title("Bar plot")

plt.suptitle("All the plots")
# plt.tight_layout(pad=1.0)
plt.show()

data = {
    'a': np.random.randint(0, 10, 30),
    'b': np.random.randint(0, 20, 30),
    'c': np.random.randint(0, 100, 30),
    "size": np.random.randint(0, 10, 30) * 50
}
plt.scatter('a', 'b', c='c', s="size", data=data)
plt.show()

from matplotlib.image import imread

img = imread("image.jpg")
print(img.shape)

plt.imshow(img, cmap=plt.get_cmap("gray"))
plt.show()

plt.imshow(img)
plt.axis("off")
plt.show()

plt.imshow(img)
plt.axis("off")
plt.show()

plt.figure(figsize=(10, 20))
plt.imshow(img)
plt.axis("off")
plt.show()

import cv2
img = cv2.imread("image.jpg", 0)

plt.imshow(img) #, cmap="gray")
plt.axis("off")
plt.show()

rand_numbers = np.random.random((7, 4))
dates = pd.date_range("20210309", periods=7)
df = pd.DataFrame(rand_numbers,
                  index=dates,
                  columns=["00.00", "06.00", "12.00", "18.00"])
df

df.plot()

df.plot(kind="bar", rot=25)

df["00.00"].plot()

df.loc[:, ["00.00", "18.00"]].plot(kind="barh")