# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SIRebhLR6Lu3kak0fU6sbyd0HlITUZnx
"""

import pandas as pd
import numpy as np

pd.Series([10, -5, 1.1, 77.7])

pd.Series([10, -5, 1.1, 77.7], index=["Chandler", "Bing", "Bender", "Rodriguez"])

data = {
    "isim": ["Ahmet", "Ezgi", "Mehmet", "Sevda"],
    "boy": [180, 170, 150, np.nan],
    "ayakkabi_no": [42, np.nan, 39, 36],
    "kilo": [80, 50, 70, 45]
}

from pprint import pprint
pprint(data)

rand_numbers = np.random.random((7, 4))

df = pd.DataFrame(rand_numbers)
df

df = pd.DataFrame(rand_numbers, columns=["00.00", "06.00", "12.00", "18.00"])
df

dates = pd.date_range("20210309", periods=7)
dates

df = pd.DataFrame(rand_numbers,
                  index=dates,
                  columns=["00.00", "06.00", "12.00", "18.00"])
df

df.dtypes

df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20210309"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "validation", "train"]),
        "F": "foo",
    }
)
df2

df2.dtypes

df.head()

df.head(2)

df.tail()

df.tail(2)

df.index

df.columns

df.to_numpy()

df.describe()

arr = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
arr.T

df.sort_index(axis=0, ascending=False)

df.sort_index(axis=1, ascending=False)

df.sort_values(by="06.00")

df["06.00"]

df[0: 3]

df[0,:]

dates[0]

df.loc[dates[0]]

df.loc["20210312": "20210314", ["00.00", "18.00"]]

import time

start = time.time()
print("Değer:", df.loc["2021-03-14", "00.00"])
print(time.time()-start)

start = time.time()
print("Değer:", df.at["2021-03-14", "00.00"])
print(time.time()-start)

df.iloc[0:4, 0:2]

df.iloc[[0, 2, 4], [2, 3]]

df[df["12.00"] > 0.5]

df2 = df

print(df2.iloc[0, 0])
df2.iloc[0, 0] = "HAHA"

df2

df

df.loc["2021-03-13": "2021-03-14", "06.00": "12.00"] = np.nan
df

df.dropna(how="any")

df

df.dropna(how="all", axis=1)

df.fillna(value=0)

df

df.isna()

df.mean()

df.mean(axis=1)

df.apply(lambda x: x.max())

df.apply(lambda x: x.sum(), axis=1)

df

df.apply(np.cumsum)

df3 = pd.DataFrame([
                    [1, 2, 3],
                    [4, 5, 6]
])
df3

pieces = [df3[:1], df3, df3[2:]]

pd.concat(pieces)

first = pd.DataFrame({"key": ["value1", "value2"], "left-val": [1, 2]})
second = pd.DataFrame({"key": ["value1", "value2"], "right-val": [3, 4]})
print(first)
print("#"*20)
print(second)

pd.merge(first, second, on="key")

df

df4 = pd.DataFrame(data)
df4

data = {
    "isim": ["Ahmet", "Ezgi", "Mehmet", "Sevda", "Ezgi"],
    "boy": [180, 170, 150, 160, 150],
    "ayakkabi_no": [42, 37, 39, 36, 38],
    "kilo": [80, 50, 70, 50, 60]
}
df4 = pd.DataFrame(data)

df4.groupby("kilo").mean()

df4.groupby(["boy", "kilo"]).mean()

